import type { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
  PiBlueprintFill,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiReact,
  SiUnity,
  SiUnrealengine,
  SiCplusplus,
  SiAdobelightroom,
  SiAdobephotoshop,
  SiAdobexd,
  SiBlender,
  SiAdobe,
  SiRender,
  SiTypescript,
} from "react-icons/si";

import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaX,
  FaThreads,
  FaInstagram,
  FaXTwitter,
  FaFacebook,
  FaPinterest,
  FaWhatsapp,
  FaReddit,
  FaTelegram,
  FaArtstation,
  FaPython,
  FaLightbulb,
  FaAt,
  FaFileInvoice,
  FaInbox,
  FaFileSignature,
  FaFileLines,
  FaBrush,
  FaBuffer,
  FaDiagramProject,
  FaConfluence,
  FaJira,
  FaDiceD20,
  FaDroplet,
  FaDrawPolygon,
  FaExplosion,
  FaShareNodes,
  FaTrowelBricks,
  FaGaugeHigh,
  FaShirt 

} from "react-icons/fa6";
import { TbBrandCSharp } from "react-icons/tb";
import { IoIosPaper } from "react-icons/io";
import { GiStoneSphere, GiMonkey  } from "react-icons/gi";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: FaAt,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  artstation: FaArtstation,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  react: SiReact,
  unity: SiUnity,
  csharp: TbBrandCSharp,
  cplusplus: SiCplusplus,
  unrealengine: SiUnrealengine,
  blueprint: PiBlueprintFill ,
  adobexd: SiAdobexd,
  adobephotoshop: SiAdobephotoshop,
  adobelightroom: SiAdobelightroom,
  blender: SiBlender,
  substancepainter: SiAdobe,
  substancedesigner: SiAdobe,
  marvelousdesigner: FaShirt,
  marmosettoolbag: GiMonkey,
  resume: FaFileLines,
  typescript: SiTypescript,
  python: FaPython,
  shader: GiStoneSphere,
  lighting: FaLightbulb,
  brush: FaBrush,
  stack: FaBuffer,
  profiler: FaGaugeHigh,
  shadergraph: FaDiagramProject,
  vfxgraph: FaExplosion,
  jira: FaJira,
  confluence: FaConfluence,

};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
